swagger: "2.0"
info:
  version: "0.0.1"
  title: Rafiki
# during dev, should point to your local machine
host: localhost:10010
# basePath prefixes all resource paths 
basePath: /
# 
schemes:
  # tip: remove http to make production-grade
  - http
  - https
# format of bodies a client can send (Content-Type)
consumes:
  - application/json
# format of the responses to the client (Accepts)
produces:
  - application/json
paths:
  /nivel/{id}:
      # our controller name
    x-swagger-router-controller: nivel
    get:
      description: Obtener un nivel capturado por id
      operationId: getNivelId
      # define the type of response for Success "200" and Error
      parameters:
        - name: id
          type: string
          in: path
          required: true
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/Nivel"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
    put: 
      description: Actualizar nivel ingresado por id
      operationId: updateNivel
      # define the type of response for Success "200" and Error
      parameters:
        - name: id
          type: string
          in: path
          required: true
        - name: data
          description: Atributos Nivel
          in: body
          required: true
          schema:
            $ref: "#/definitions/Nivel"
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/Nivel"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
    delete: 
      description: eliminar el nivel ingresado por id
      operationId: deleteNivel
      # define the type of response for Success "200" and Error
      parameters:
        - name: id
          type: string
          in: path
          required: true
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/Nivel"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /lista_niveles:
    # our controller name
    x-swagger-router-controller: nivel
    get:
      description: Obtener la lista de niveles académicos
      operationId: get_niveles
     # define the type of response for Success "200" and Error
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/GetUsersListResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
    post:
      description: Añadir un nuevo nivel
      operationId: createNivel
      # movie info to be stored
      parameters:
        - name: data
          description: Atributos Nivel
          in: body
          required: true
          schema:
            $ref: "#/definitions/Nivel"
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/Nivel"
  /asignaturas:
    x-swagger-router-controller: asignatura
    get:
      description: Obtener la lista de asignaturas
      operationId: getAsignaturas
      # define the type of response for Success "200" and Error
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/Asignatura"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
    post:
      description: Añadir una nueva asignatura
      operationId: postAsignatura
      # movie info to be stored
      parameters:
        - name: name
          description: Atributos Asignatura
          in: body
          required: true
          schema:
            $ref: "#/definitions/Asignatura"
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/Asignatura"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /organizaciones:
    # our controller name
    x-swagger-router-controller: organizacion
    get:
      description: Obtener la lista de organizaciones
      # define the type of response for Success "200" and Error
      operationId: getListOrganizaciones
            $ref: "#/definitions/Organizacion"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
      description: Añadir una nueva organizacion
      operationId: createOrganizacion
      parameters:
        - name: data
          description: Atributos usuario
          in: body
          required: true
          schema:
            $ref: "#/definitions/Organizacion"
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/Organizacion"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /asignaturas/{id}:
    # our controller name
    x-swagger-router-controller: asignatura
    get:
      description: Obtener un usuario
      operationId: getAsignatura
      # define the type of response for Success "200" and Error
      parameters:
        - name: id
          type: string
          in: path
          required: true
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/Asignatura"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
    put:
      description: Actualizar una asignatura
      operationId: updateAsignatura
      # define the parameters
      parameters:
        - name: id
          type: string
          in: path
          required: true
        - name: data
          description: Propiedades de Asignatura
          in: body
          required: true
          schema:
            $ref: "#/definitions/Asignatura"
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/Asignatura"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
    delete:
      description: Eliminar una Asignatura
      operationId: deleteAsignatura
      # define the parameters
      parameters:
        - name: id
          type: string
          in: path
          required: true
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/Asignatura"
  /cursos:
    # our controller name
    x-swagger-router-controller: cursos
    get:
      description: Obtener la lista de cursos
      operationId: getCursos
      # define the type of response for Success "200" and Error
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/Curso"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
    post:
      description: Añadir un nuevo curso
      operationId: postCurso
      # movie info to be stored
      parameters:
        - name: data
          description: Atributos de curso
          in: body
          required: true
          schema:
            $ref: "#/definitions/Curso"     
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/Curso"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /organizaciones/{id}:
    # our controller name
    x-swagger-router-controller: organizacion
    get:
      description: Obtener una organizacion
      operationId: getOrganizacion
      # define the type of response for Success "200  " and Error
      parameters:
        - name: id
          type: string
          in: path
          required: true
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/Organizacion"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
    put:
      description: Actualizar una organizacion
      operationId: updateOrganizacion
      # define the parameters
      parameters:
        - name: id
          description: ID de la organizacion
          type: string
          in: path
          required: true
        - name: data
          description: Propiedades de la organizacion
          in: body
          required: true
          schema:
            $ref: "#/definitions/Organizacion"
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/Organizacion"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
    delete:
      description: Eliminar organizacion
      operationId: deleteOrganizacion
      # define the parameters
      parameters:
        - name: id
          description: Id de la organizacion
          type: string
          in: path
          required: true
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/Organizacion"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"                
  /cursos/{id}:
    # our controller name
    x-swagger-router-controller: cursos
    get:
      description: Obtener un curso
      operationId: getCursoId
      # define the type of response for Success "200" and Error
      parameters:
        - name: id
          type: string
          in: path
          required: true
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/Curso"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
    put:
      description: Actualizar un curso
      operationId: putCurso
      # define the parameters
      parameters:
        - name: id
          description: Curso id
          type: string
          in: path
          required: true
        - name: name
          description: Propiedades de User
          in: body
          required: true
          schema:
            $ref: "#/definitions/Curso"
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/Curso"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"        
    delete:
      description: Eliminar curso
      operationId: deleteCurso
      # define the parameters
      parameters:
        - name: id
          description: User id
          type: string
          in: path
          required: true
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/Curso"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /users:
    # our controller name
    x-swagger-router-controller: users
    get:
      description: Obtener la lista de usuarios
      # define the type of response for Success "200" and Error
      operationId: getUsers
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/GetUsersListResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
    post:
      description: Añadir un nuevo usuario
      # movie info to be stored
      operationId: postUser
      parameters:
        - name: data
          description: Atributos usuario
          in: body
          required: true
          schema:
            $ref: "#/definitions/User"
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/User"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /users/{id}:
    # our controller name
    x-swagger-router-controller: users
    get:
      description: Obtener un usuario
      # define the type of response for Success "200" and Error
      parameters:
        - name: id
          type: string
          in: path
          required: true
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/GetUserResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
    put:
      description: Actualizar un usuario
      # define the parameters
      operationId: updateUser
      parameters:
        - name: id
          description: User id
          type: string
          in: path
          required: true
        - name: name
          description: Propiedades de User
          in: body
          required: true
          schema:
            $ref: "#/definitions/User"
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/GeneralResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
    delete:
      description: Eliminar User
      # define the parameters
      operationId: deleteUser
      parameters:
        - name: id
          description: User id
          type: string
          in: path
          required: true
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/GeneralResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /hello:
    # binds a127 app logic to a route
    x-swagger-router-controller: hello_world
    get:
      description: Returns 'Hello' to the caller
      # used as the method name of the controller
      operationId: hello
      parameters:
        - name: name
          in: query
          description: The name of the person to whom to say hello
          required: false
          type: string
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/HelloWorldResponse"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /swagger:
    x-swagger-pipe: swagger_raw
# complex objects have schema definitions
definitions:
  HelloWorldResponse:
    required:
      - message
    properties:
      message:
        type: string
  ErrorResponse:
    required:
      - message
    properties:
      message:
        type: string
  GetUsersListResponse:
    required:
      - users
    properties:
      # The array of movies
      users:
        type: array
        items: 
          type: object
          properties:
            id:
              type: string
            name:
              type: string
            rut:
              type: string
            mail:
              type: string
  Asignatura:
    type: object
    properties:
      nombre:
        type: string
        description: Nombre completo de la asignatura
      enfasis:
        type: array
        items: 
          type: string
        description: Descripcion de lo esperado para la asignatura
      horasPedagogicas:
        type: number
        description: Numero de horas
      horasPedagogicasConJecAnual:
        type: number
        description: Numero de horas anuales con jornada escolar completa
      horasPedagogicasSinJecAnual:
        type: number
        description: Numero de horas anuales sin jornada escolar completa
      horasPedagogicasConJecSemanal:
        type: number
        description: Numero de horas semanales con jornada escolar completa
      horasPedagogicasSinJecSemanal:
        type: number
        description: Numero de horas semanales sin jornada escolar completa
  Organizacion:
    type: object
    properties:
      nombre:
        type: string
      rbd:
        type: number
      descripcion:
        type: string
      reconocimientoOficial:
        type: string
      dependencia:
        type: string
      sostenedor:
        type: string
      orientacionReligiosa:
        type: string
      direccion:
        type: object
        properties:
          calle:
            type: string
          region:
            type: string
          comuna:
            type: string
      correo:
        type: string
      telefono:
        type: string
      web:
        type: string
      director:
        type: string
      numVacantes:
        type: number
      fechaPostulacion:
        type: object
        properties:
          inicio:
            type: string
          cierre:
            type: string
      mensualidad:
        type: number
      totalAlumnosMatriculados:
        type: number
      promAlumnosCurso:
        type: number
      puntajeSimce:
        type: number
  User:
    type: object
    properties:
      _id:
        type: string
      _v:
        type: number
      nombre:
        type: string
        description: Nombre completo del usuario
      rut:
        type: string
        description: RUT del usuario
      correo:
        type: string
        description: Correo del usuario
      role:
        type: array
        items:
          type: string
        description: Tipo de usuario
  Nivel:
    type: object
    properties:
      sigla:
        type: string
        description: Nombre completo del usuario
      tipo_nivel:
        type: string
        description: RUT del usuario
      grado:
        type: number
        description: Correo del usuario
      descripcion:
        type: string
        description: descripción del nivel
      decreto:
        type: string
        description: Decreto para el nivel académico
  GeneralResponse:
    type: object
    properties:
      success:
        type: number
        description: returns 1 if successful
      message:
        type: string
        description: a short comment 
    required:
      - success
      - message
  GetUserResponse:
    required:
      - id
      - name
      - rut
    properties:
      id:
        type: string
      name: 
        type: string
      rut:
        type: string
      mail:
        type: string
  Curso:
    type: object
    properties:
      idCurso:
        type: string
        description: Sigla del curso (Ejemplo 1A)
      nivel:
        type: string
        description: Nivel educacional del curso
      asignatura:
        type: string
        description: Nombre de la asignatura
      profesorJefe:
        type: string
        description: Nombre del profesor jefe del curso
      salaCurso:
        type: string
        description: Sala del curso
      totalAlumnos:
        type: number
        description: Cantidad total de alumnos del curso